Test result

diff --git a/.github/actions/job_id/action.yml b/.github/actions/job_id/action.yml
--- a/.github/actions/job_id/action.yml
+++ b/.github/actions/job_id/action.yml
@@ -19,12 +19,12 @@ runs:
   using: 'composite'
   steps:
 
-  # - name: Debug
-  #   id: debug
-  #   shell: bash
-  #   run: |
-  #     echo "github ${{ toJSON(github) }}"
-  #     echo "github.job ${{ toJSON(github.job) }}"
+  - name: Debug
+    id: debug
+    shell: bash
+    run: |
+      echo "github.job ${{ toJSON(github.job) }}"
+      echo "github ${{ toJSON(github) }}"
 
   - name: Fetch Job ID
     id: fetch-job-id
@@ -37,4 +37,8 @@ runs:
         "https://api.github.com/repos/${{ github.repository }}/actions/runs/${workflow_id}/jobs")
       job_id=$(echo "$response" | jq -r --arg job_name "$job_name" '.jobs[] | select(.name == $job_name) | .id')
       echo $job_id
+      if ! [[ "$job_id" =~ ^[0-9]+$ ]]; then
+        echo "Error: Job ID not found" >&2
+        exit 1
+      fi
       echo "job_id=$job_id" >> $GITHUB_OUTPUT
