Fix for workflows that has more than 100 jobs

diff --git a/.github/actions/job_id/action.yml b/.github/actions/job_id/action.yml
--- a/.github/actions/job_id/action.yml
+++ b/.github/actions/job_id/action.yml
@@ -23,17 +23,37 @@ runs:
     id: fetch-job-id
     shell: bash
     run: |
-      job_name="${{ inputs.job_name }}"
+      JOB_NAME="${{ inputs.job_name }}"
       workflow_id="${{ github.run_id }}"
-      attempt_id="${{ github.run_attempt }}"
-      response=$(curl -s -H "Authorization: token ${{ inputs.gh_token }}" \
-        "https://api.github.com/repos/${{ github.repository }}/actions/runs/${workflow_id}/jobs?per_page=1000")
-      job_id=$(echo "$response" | jq -r '.jobs[] | select(.name | contains("${{ inputs.job_name }}")) | .id ')
-      echo $job_id
-      if ! [[ "$job_id" =~ ^[0-9]+$ ]]; then
-        echo "Error: Job ID not found" >&2
-        echo "JOB NAMES"
-        echo "$response" | jq -r '.jobs[] | .name '
-        exit 1
+      repo=${{ github.repository }}
+
+      page=1
+      per_page=90
+      job_id=""
+
+      while true; do
+          response=$(curl -s -H "Authorization: token ${{ inputs.gh_token }}" \
+              https://api.github.com/repos/$repo/actions/runs/$workflow_id/jobs?per_page=$per_page&page=$page")
+
+          job_id=$(echo "$response" | jq -r --arg JOB_NAME "$JOB_NAME" '.jobs[] | select(.name == $JOB_NAME) | .id')
+
+          if [ -n "$job_id" ]; then
+              echo "Job ID for job name '$JOB_NAME' is: $job_id"
+              break
+          fi
+
+          # Check if we have more pages to fetch
+          next_page=$(echo "$response" | jq -r '.total_count')
+          if [ "$((page * per_page))" -ge "$next_page" ]; then
+              break
+          fi
+
+          page=$((page + 1))
+      done
+
+      if [ -z "$job_id" ]; then
+          echo "Job name '$JOB_NAME' not found in workflow ID '$workflow_id'."
+          exit 1
       fi
+
       echo "job_id=$job_id" >> $GITHUB_OUTPUT
